---
- name: Create multiple VMs from CSV data
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read VM data from CSV
      read_csv:
        path: /home/ubuntu/ansible/create_vms_from_csv/vms.csv
        delimiter: ','
      register: csv_data

    - name: Create VMs
      vmware_guest:
        hostname: "{{ 192.168.1.11 }}"
        username: "{{ administrator@vsphere.local }}"
        password: "{{ VMware!2345 }}"
        validate_certs: no
        folder: Templates
        template: Ubuntu-2204-Template-100GB-Thin
        datacenter: NSX
        name: "{{ item.vm_name }}"
        networks:
          - name: prod-vds-mgt
            ip: "{{ item.ip_address }}"
            gateway: "{{ item.gateway }}"
            netmask: "255.255.255.0" # Adjust as needed
            dns_servers: 
              - "{{ item.dns_server }}"
      loop: "{{ csv_data.list }}"
